class GladeException(Exception):
    ...
    
class PyParserException(GladeException):
    ...
    
class NoProgrammeSpecified(PyParserException):
    ...
    
class NoClosingParenthesis(PyParserException):
    ...