class GladeException(Exception):
    ...
    
class NotImplementedError(GladeException):
    ...
    
class PyParserException(GladeException):
    ...

class NoProgrammeSpecified(PyParserException):
    ...
    
class NoClosingParenthesis(PyParserException):
    ...
    
class ParserSyntaxError(PyParserException):
    ...